version: '3.4'

services:
  useragentapi:
    image: ${DOCKER_REGISTRY-}useragentapi
    build:
      context: .
      dockerfile: UserAgentApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=Postgres;Database=your_db;Username=your_user;Password=your_password
    depends_on:
      - postgres
    ports:
      - "8080:80"
      - "8081:8081"
  
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
